version: '3.8'
services:
  nodeapp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - REACT_APP_API_BASE_URL=http://192.168.4.223:3001/api
    volumes:
      - .:/usr/src/app
    command: npm start
